name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    uses: Geode-solutions/actions/.github/workflows/docker-build-squash-push.yml@master
    with:
      tag: 'master'
      google: false
    secrets: 
      TOKEN: ${{secrets.GITHUB_TOKEN}}
